spring:
  application:
    name: jwtAuthProject
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    password: password
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 8005
security :
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
#logging.level.org.springframework.security=DEBUG
logging:
  level:
    org:
      springframework:
        security:
          DEBUG
